export const otherPortOptions = [
  {
    cnName: "宁波",
    code: "CNNBO",
    countryCnName: "中国",
    countryCode: "CN",
    countryEnName: "China",
    countryId: "248",
    createTime: "2023-10-25 16:50:11",
    enName: "Ningbo",
    enabled: true,
    id: "248000103",
    isFnd: false,
    isPopularity: true,
    isPor: true,
    remark: null,
    routeCode: "AS/CN",
    routeId: "1024",
    routeName: "中国",
    routeParentCode: "AS",
    routeParentName: "亚洲线",
    updateTime: "2023-10-25 16:50:11",
  },
  {
    id: "248000104",
    cnName: "上海",
    code: "CNSHA",
    enName: "Shanghai",
    countryName: "China",
    countryLocalName: "中国",
  },
  {
    id: "248000105",
    cnName: "广州",
    code: "CNGZ",
    enName: "Guangzhou",
    countryName: "China",
    countryLocalName: "中国",
  },
  {
    id: "248000106",
    cnName: "青岛",
    code: "CNQIN",
    enName: "Qingdao",
    countryName: "China",
    countryLocalName: "中国",
  },
  {
    id: "248000107",
    cnName: "深圳",
    code: "CNSZX",
    enName: "Shenzhen",
    countryName: "China",
    countryLocalName: "中国",
  },
  {
    id: "248000108",
    cnName: "厦门",
    code: "CNXMN",
    enName: "Xiamen",
    countryName: "China",
    countryLocalName: "中国",
  },
];
