export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/memberUnit/index",
    "pages/affiliate/editAffiliateImage/index",
    "pages/affiliate/editAffiliateAdvantage/index",
    "pages/profile/index",
    "pages/affiliate/editAffiliateBase/index",
    "pages/login/index",
    "pages/message/index",
    "pages/affiliate/index",
    "pages/collection/index",
    "pages/dynamic/index",
    "pages/logistics-tracking/index",
    "pages/logistics-tracking/logistics-tracking-detail/index",
    "pages/dynamic/dynamicForm/index",
    "pages/unitGeneral/index",
    "pages/application/ApplicationForm/index",
    "pages/consulting/index",
    "pages/application/index",
    "pages/memberUnit/memberUnitDetail/index",
    "pages/profile/AccountSetting/AccountSettingEdit",
    "pages/profile/AccountSetting/index",
    "pages/webview/index",
    "pages/affiliate/editCustomer/index",
    "pages/industryDynamics/index",
    "pages/memberUnit/memberUnitPicture/index",
  ],
  permission: {
    "scope.writeStorage": {
      desc: "需要写入存储空间以保存文件",
    },
  },
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
  tabBar: {
    color: "#909399",
    selectedColor: "#1677FF",
    backgroundColor: "#FFFFFF",
    list: [
      {
        pagePath: "pages/index/index",
        text: "首页",
        iconPath: "images/home.png",
        selectedIconPath: "images/home-selected.png",
      },
      {
        pagePath: "pages/memberUnit/index",
        text: "会员单位",
        iconPath: "images/memberUnit.png",
        selectedIconPath: "images/memberUnit-selected.png",
      },
      {
        pagePath: "pages/profile/index",
        text: "我的",
        iconPath: "images/profile.png",
        selectedIconPath: "images/profile-selected.png",
      },
    ],
  },
});
